### ISSUE TITLE
external tags are always placed at time 0

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#100]
this has been fixed by 9616bd0541348ab0d59eacef0e2b5b4736bf5a99 but this ticket is to track release on pypi

**Comment by swharden** [comment]
now on pypi

```
pip install --upgrade pyabf
```

**Comment by KBenthall** [comment]
I am also having this issue even though I updated to pyabf 2.2.6

**Comment by swharden** [comment]
@KBenthall I'm sorry to hear this is the case! Can you use this comment box to upload an example of an ABF file which has an improperly-placed external tag? The one I have `ch121219_1_0001.abf` does seem to work, so I'm interested to learn more about what makes your new ABFs fail. Thanks!

**Comment by swharden** [comment]
Oh hey, I just saw your email. I'll upload that example ABF here and start working on it shortly. I'll let you know what I find!

[2020_07_29_0062.zip](https://github.com/swharden/pyABF/files/5001600/2020_07_29_0062.zip)

**Comment by KBenthall** [comment]
Thank you so much!!

**Comment by swharden** [comment]
2020_07_29_0062 as been analyzed and its header is here:
https://github.com/swharden/pyABF/blob/master/data/headers/2020_07_29_0062.md

In the header we find `TagSection = [1476, 64, 1]`
Meaning at byte `1476*512` (`755712`) in the ABF there is `1` tag entry `64` bytes long.

![image](https://user-images.githubusercontent.com/4165489/89087596-c6930100-d362-11ea-985b-17bb0544fca3.png)

Now according to ABF1 notes https://swharden.com/pyabf/abf1-file-format.md.html#the-abf-tag-section this should contain:
* 4-byte `UInt32` tag time
* 56-byte `char` tag comment
* 2-byte `short` tag type (0 for time tag, 1 for comment tag, 2 for external tag, 3 for voice tag)
* 2-byte `short` voice tag number (if tag type is 3)

For us these 4 values are: `18432`, `Digital Outputs => 00000001`, `1`, `0`

...so a non-zero number is there for tag time. Typically I transform it from fSynch time units to seconds like:
```python
tagTimesSec = [x*fSynchTimeUnit/1e6 for x in lTagTime]
```

so I suspect with this file the comment system is okay, but there's something wrong with `fSynchTimeUnit`...

Could it be that if `fSynchTimeUnit == 0` the tag time is in # of samples? This ABF is 2-channels recorded at 10kHz (20kHz effective sample rate). `18432 / 20000 = 921.6` which is the time (in milliseconds) displayed in ClampFit. I think this may be a solution 🤔

**Comment by swharden** [comment]
I just made the change and think I got this working! I'll release pyABF 2.2.7 on pyPI in a few minutes, then you can:

```
pip install --upgrade pyabf
```

Thanks again for sending in your ABF file 👍 

### Demo
```python
abf = pyabf.ABF(DATA_FOLDER+"/2020_07_29_0062.abf")

plt.figure(figsize=(10, 4))
plt.plot(abf.sweepX, abf.sweepY, lw=.5)

for tagIndex, tagTimeSec in enumerate(abf.tagTimesSec):
    print(f"tag '{abf.tagComments[tagIndex]}' at {tagTimeSec} sec")
    plt.axvline(tagTimeSec, color='r', ls=':')

plt.ylabel(abf.sweepLabelY)
plt.xlabel(abf.sweepLabelX)
plt.title(abf.abfID)
plt.margins(0, .05)
plt.tight_layout()
plt.show()
```

### Output
```
tag 'Digital Outputs => 00000001' at 0.9216 sec
```

![image](https://user-images.githubusercontent.com/4165489/89088166-ecb9a080-d364-11ea-9c5a-801d13864a5e.png)

**Comment by KBenthall** [comment]
This is so great, thank you so much!! 😄
