### ISSUE TITLE
how to display command current (sweepC vs. channel=1)

### ISSUE THREAD

**Issue by mercedes-gonzalez** [swharden/pyABF#106]
Hi! I was wondering if you know if the sweepC variable should be updating with each sweep in a file (perhaps does it depend on how the inputs are defined)? I have a protocol defining the current input command by the user list, so I'm not sure if sweepC would update accordingly or if it is saved differently than a typical epoch definition. 

This is what my data looks like in Axograph, however sweepC is the same for every sweep instead of the incremented current as shown below. 

![Capture](https://user-images.githubusercontent.com/30077395/77671656-4e54a300-6f5e-11ea-810a-1995b03f88cd.PNG)

Thank you for any guidance! Also this whole project is super useful!

**Comment by swharden** [comment]
Hi @mercedes-gonzalez, 

I suspect the data you are looking for is in another channel (not the epoch waveform provided by sweepC). To access data from the second channel try something like:

```python
abf = pyabf.ABF("file.abf")

abf.setSweep(sweepNumber, channel=0)
print("first channel:", abf.sweepY)

abf.setSweep(sweepNumber, channel=1)
print("second channel:", abf.sweepY)
```

Let me know if that does the trick!

**Comment by mercedes-gonzalez** [comment]
It appears not. I can see the smallest magnitude current step in channel 0, but it is saved as the same current step in each sweep. So there is data stored in channel 0 it's just not what I would expect. The only other channel I can access is zeros across the board for each sweep.

**Comment by swharden** [comment]
> Ah I see yes, it was not saved as a command, it was saved as the dependent variable. Thank you for your help!

Glad it worked! This seems to be a common question (#105) so I added a note to the tutorial which hopefully clarifies this issue for future users.

https://swharden.com/pyabf/tutorial.php#command
