### ISSUE TITLE
Memory usage builds up when iteratively open abf files

### ISSUE THREAD

**Issue by javierzsm** [swharden/pyABF#125]
Hi, 

I noticed that when I do batch analysis and iteratively open many abf files, memory usage builds up even though I overwrite the pyABF.ABF instance each time keeping only one instance during the whole program.

When the number of files is large enough, memory saturates and kernel restarts.

This is true even if the loop doesn't do anything but opening one abf at the time.

Any clue of how to avoid it?

Thanks

![Screenshot from 2022-02-11 14-40-09](https://user-images.githubusercontent.com/18037746/153605370-08dce2b7-8f89-4a1a-8ae5-3d127478c3ae.png)

**Comment by swharden** [comment]
Hi @javierzsm, thanks for reporting this! I can take a closer look this evening.

Can you share the code you are using to iteratively open many ABF files?

**Comment by javierzsm** [comment]
Hi @swharden 
Thanks a lot for your quick reply.
I copy below the piece of code that reproduce the issue. 
I just noticed that it becomes appreciable when opening files => 60-70 Mb each; with smaller files it builds up but more slowly.
Thanks,
Javier

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 11 15:29:52 2022

@author: javier
"""
import pyabf
import os

path_data = r'/home/javier/Lab/Data/Ephys/'

for nom_file in os.listdir(path_data):
    # Load abf
    if nom_file.endswith('.abf'):
        print('\nOpening file %s' % nom_file)
        abf = pyabf.ABF(path_data + '/' + nom_file)

**Comment by swharden** [comment]
Hi @javierzsm, 

I do not think this is a bug. I think this is the natural management of memory by Python's garbage collector.

Here's sample code I used to benchmark how much memory is used as I re-load the same ABF files 5,000 times:

![image](https://user-images.githubusercontent.com/4165489/153687655-019afb15-f653-4286-a1c3-a6148b05a435.png)

```py
import sys
import pathlib
import tracemalloc
import os
import matplotlib.pyplot as plt
import pyabf

if __name__ == "__main__":

    abfPath = "2020_06_16_0001.abf"
    repetitions = 5000
    memoryPerLoad = []

    tracemalloc.start()
    for i in range(repetitions):
        abf = pyabf.ABF(abfPath)
        memory = tracemalloc.get_traced_memory()[0]/1e6
        memoryPerLoad.append(memory)
        print(f"{i+1} of {repetitions}... current memory: {memory} MB")
    tracemalloc.stop()

    plt.plot(memoryPerLoad)
    plt.title(os.path.basename(abfPath))
    plt.grid(ls='--', alpha=.5)
    plt.ylabel("Process Memory (MB)")
    plt.xlabel("ABF Read Count")
    plt.show()
```

If you want to _force_ Python's garbage collector to run manually you can, but this is typically not recommended https://docs.python.org/3/library/gc.html

Do you think this explanation adequately addresses your issue? If you can provide or a sample ABF and sample code that lets me reproduce a bug on my side I'd be happy to look deeper into this. Thanks, and good luck! 👍 🚀

**Comment by swharden** [comment]
It may be worth trying to call the garbage collector manually after loading huge files to see if it helps... something like this:

```py
import pyabf
import gc

for i in range(repetitions):
    abf = pyabf.ABF("test.abf")
    gc.collect()
```

**Comment by swharden** [comment]
Oh! Also I now see you're running that from inside Spyder/IPython.

Does this issue go away if you run it from a console in regular Python?

**Comment by javierzsm** [comment]
Thanks Scott!
The issue also raises when running on regular python from bash, that was the first thing I tried.
However, you seem to have spotted what the issue was as calling the garbage collector solved the issue (and made me learn about it!).
Thanks, this was very helpful!
