### ISSUE TITLE
Tutorial code - Plot the Command Waveform

### ISSUE THREAD

**Issue by ondrejtichacek** [swharden/pyABF#126]
Hi!
The documentation for the [Plot the Command Waveform](https://swharden.com/pyabf/tutorial/#plot-the-command-waveform) contains a code from the previous section, and the code needed to reproduce the figure below is missing.

**Comment by swharden** [comment]
Thanks for reporting this @ondrejtichacek! It is fixed now, but feel free to follow-up if you find anything else or if any questions come up 👍
