### ISSUE TITLE
Folder loop with pyabf

### ISSUE THREAD

**Issue by chalmers4c** [swharden/pyABF#133]
Hello

I have a folder of couple of abf files, I have written a script to use pyabf to loop the folder through glob. Basically, all have same sweep and channel (both 0, 0) setting, i want to loop through them, plot a XY scatter of the trace, save the figure.
Below for the function i wrote to open abf file
def pyabf_trace(Path):
    trace_abf = pyabf.ABF(Path)
    trace_current = trace_abf.setSweep(sweepNumber = 0, channel = 0)
    trace_current_time = trace_abf.sweepX
    trace_current_current = trace_abf.sweepY
    return trace_current_time, trace_current_current, trace_abf

Below for the function i wrote, folder_path is from tkinter where I select a folder. Plot_trace() is a function to plot a ax.scatter of the Time_axis and Current_axis. I will print correctly the new path, but somehow it just keep on plotting the first abf that was loaded (i.e. only the 1st file is plotted and this is getting plotted repeatedly for however many files I have got in the folder). But the same traces were named properly (e.g. I have three abf trace - A.abf, B.abf and C.abf. It will plot A.abf three times, but the saved figures are A.png, B.png and C.png), so I know the path/file name has been read properly. But somehow the sweep from B.abf is not read properly.

save_to_path is just plt.savefig().

def Batch_Trace_Process():
    Folder_path = folder_path()
    trace_files = pathlib.Path(Folder_path).glob('*.abf')
    for trace_file in trace_files:
        print(trace_file)
        try:
            Time_axis, Current_axis, trace_abf = pyabf_trace(trace_file)
            Plot_trace()
            File_name = trace_file.stem
            save_to_path(Path = Folder_path, Name = File_name)
            plt.close()
        except:
            pass
        continue
    print('Finished Processing')

**Comment by chalmers4c** [comment]
Solved the issue, it was my side's problem.

**Comment by swharden** [comment]
Hi @chalmers4c, I'm glad you figured this one out! Thanks for following-up 👍
