### ISSUE TITLE
Acces to Telegraphed Gain

### ISSUE THREAD

**Issue by Asrilioss** [swharden/pyABF#137]
Hi,

I didn't find a way to acces to the Telegraphed Gain of the Digitizer channel. I dont know if is possible to do so, I have acces to it if I double click on "Vm_scaled" in Clampfit for exemple it show Signal : Name, Units, V/mV, @ 0 V and telegraphed gain. But accessing it by coding would be perfect.

I ask that to code something how check if the gain didn't change between two folders.

Thanks you,

**Comment by swharden** [comment]
Hi @Asrilioss, this may be possible! It's a lot of info, but if you inspect the ABF header like this you may find the variable name you're looking for:

https://swharden.com/pyabf/tutorial/#inspect-the-abf-header

**Comment by swharden** [comment]
Maybe something like

```py
print(myAbf._adcSection.fTelegraphAdditGain[0]) # the zero is the ADC channel, and you may need to try several numbers to get it right
```

**Comment by Asrilioss** [comment]
Yeah I just found that looking at headerV2, thanks you for your answers and a fast one, this work perfectly, do you know if is a value I can change ? 
Ty
