### ISSUE TITLE
How to read a single sweep without loading the entire ABF into memory

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#138]
From Kyle via email:

> I am working on a data analysis project that involves loading a very large number of ABF files, but only requires access to a small subset of them at any given time. From what I can see of the pyABF library, the _loadAndScaleData function is only called once on initialization and fully loads the whole file into memory. Is it possible in the current implementation of pyABF to load and scale only a subset of the data in an ABF file, say "give me the data in channel 0, sweepY, between timestamps T1 and T2"? and have it load that from disk on the fly?

**Comment by swharden** [comment]
here's the code that, when called, loads all sweeps at once

https://github.com/swharden/pyABF/blob/06247e01ca3c19f5419c3b9b2207ee544e30dbc5/src/pyabf/abf.py#L466-L484

A simple fix may be to add an optional argument `onlySweep` which, if specified, only populates the `self.data[i]` for the `i` specified by that argument 🤔

**Comment by shadowk29** [comment]
Another approach using memmap, assuming you can extract data format in a compatible string:
```
columntypes = np.dtype([('channel_1', header.get_data_format()), ('channel_2', header.get_data_format())]) 
raw_data_channel_1 = np.memmap(filename, dtype=columntypes, offset=header.get_header_bytes())['channel_1']
```
this just memmaps the file without loading it into memory, while still allowing you to index into it like a numpy array downstream. Gives some flexibility. 

My own version of this was started before I discovered your library so isn't directly mappable to your architecture at this point, but I may be able to port it over.

**Comment by swharden** [comment]
Here's a test program I'm using to evaluate memory utilization

```py
import sys
import pathlib
import psutil
import pyabf

environment_kb = None
def printMemoryUsage(message = ""):
    global environment_kb
    kb = psutil.Process().memory_info().rss / 1000
    if not environment_kb:
        environment_kb = kb
    kb = int(kb - environment_kb)
    print(f"{message} {kb:,} KB")


if __name__ == "__main__":
    printMemoryUsage("environment")
    abf = pyabf.ABF("vc_drug_memtest.abf", loadData=False)
    printMemoryUsage("after reading header")
    for i in range(5):
        abf.setSweep(i)
        printMemoryUsage(f"after loading sweep {i}")
```

It shows how the memory jumps to max the first time a sweep is loaded

```
environment 0 KB
after reading header 344 KB
after loading sweep 0 78,680 KB
after loading sweep 1 78,991 KB
after loading sweep 2 78,995 KB
after loading sweep 3 78,995 KB
after loading sweep 4 78,995 KB
```

**Comment by swharden** [comment]
Hi @shadowk29, looking at this closer, it looks like `abf.data` is expected to always be a 2D numpy array sized to hold all the values from all sweeps.

Even if we attempt to read only one sweep from disk, the current architecture of `_loadAndScaleData` and `abf.data` is such that a large amount of memory will be used if lots of ABFs are opened simultaneously. There's probably not a clean fix here that doesn't require significant refactoring which I'm less inclined to pursue.

However, there are two solutions to your challenge:

1) Modify your code to load an ABF, extract the piece of it you need, then remove the `ABF` object from memory. You keep only the little segment you need, and this problem goes away

2) Create a custom `GetSweepFromFile()` method that bypasses `_loadAndScaleData()` and does not use `SetSweep()` at all. I'll explore this a bit and see if I can come up with a working code example. 

Both options are nice because they do not require editing the source code or deploying a new package

**Comment by shadowk29** [comment]
Now try with an ABF file that's bigger than available RAM - the issue is that it loads the full file contents into memory and that is not always feasible.
________________________________

**Comment by swharden** [comment]
> Now try with an ABF file that's bigger than available RAM

lol, what are you guys studying 🤪

I'm working on a method to do this now and am optimistic it will work well! It will be nice to include this into the source and publish a new package after all 🚀

**Comment by swharden** [comment]
Hi @shadowk29, try this! You can run it in your own code. If it works well, I can built it into pyABF for a future release. I'm looking forward to your feedback!

```py
def getOnlySweep(abf, sweepIndex: int):
    with open(abf.abfFilePath, 'rb') as fb:
        pointsPerSweep = int(abf.dataPointCount / abf.sweepCount)
        bytesPerSweep = int(pointsPerSweep * abf.dataPointByteSize)
        sweepByteOffset = bytesPerSweep * sweepIndex
        fb.seek(abf.dataByteStart + sweepByteOffset)
        raw = np.fromfile(fb, dtype=abf._dtype, count=pointsPerSweep)
        nRows = abf.channelCount
        nCols = int(pointsPerSweep/abf.channelCount)
        raw = np.reshape(raw, (nCols, nRows))
        raw = np.transpose(raw)
        raw = raw.astype(np.float32)
        if abf._dtype == np.int16:
            for i in range(abf.channelCount):
                raw[i] = np.multiply(raw[i], abf._dataGain[i])
                raw[i] = np.add(raw[i], abf._dataOffset[i])
        return raw
```

```py
abf = pyabf.ABF("test.abf", loadData=False)
for i in range(5):
    values = getOnlySweep(abf, i)
    print(values)
```

**Comment by shadowk29** [comment]
Pretty much there - I think the only change I would suggest is to allow loading of a specific part of a sweep. In principle a single sweep could be larger than RAM (we have very high bandwidth measurements), so the template would be

def getOnlySweep(abf, sweepIndex: int, startPoint: int, endPoint: int):

and load only data between index startPoint and endPoint for the specified sweep.

Does that make sense?

________________________________

**Comment by swharden** [comment]
> the only change I would suggest is to allow loading of a specific part of a sweep

Good idea! I can adapt the method above to look something like:

```py
def getOnlySweep(abf, sweepIndex: int, startTime: float, endTime: float):
```

Where times are specified in seconds

**Comment by shadowk29** [comment]
That would be perfect
________________________________

**Comment by swharden** [comment]
Hi @shadowk29, I think this works as expected. Can you double-check it with your large ABFs? If you report that it works well, I'll built it into the ABF class and release a new package 👍 

```py
def getOnlySweep(abf: pyabf.ABF, sweepIndex: int, startTime: float = None, endTime: float = None):
    """
    Return values for a sweep (one row per channel) by reading directly from the ABF file.
    Use this to avoid storing large amounts of sweep data in memory.

    ### Parameters
    * `abf` - ABF the sweep data will be read from
    * `sweepIndex` - The sweep number (starting at zero). Note that all channels for this sweep will be returned.
    * `startTime` - Data returned will begin at this time within the sweep (in seconds)
    * `endTime` - Data returned will end at this time within the sweep (in seconds)
    """

    startTime = startTime if startTime else 0
    startTime = max(0, startTime)

    endTime = endTime if endTime else abf.sweepLengthSec
    endTime = min(endTime, abf.sweepLengthSec)

    bytesPerSample = int(abf.dataPointByteSize)
    bytesPerSecond = int(abf.dataPointByteSize * abf.sampleRate)
    samplesPerSweep = int(abf.dataPointCount / abf.sweepCount)
    bytesPerSweep = samplesPerSweep * bytesPerSample
    sweepFirstByte = abf.dataByteStart + bytesPerSweep * sweepIndex
    startTime = startTime if startTime else 0
    sweepFirstByte += int(startTime * bytesPerSecond)
    endTime = endTime if endTime else abf.sweepLengthSec
    sampleCount = (endTime - startTime) * abf.sampleRate

    with open(abf.abfFilePath, 'rb') as fb:
        fb.seek(sweepFirstByte)
        raw = np.fromfile(fb, dtype=abf._dtype, count=sampleCount)
        nRows = abf.channelCount
        nCols = sampleCount
        raw = np.reshape(raw, (nCols, nRows))
        raw = np.transpose(raw)
        raw = raw.astype(np.float32)
        if abf._dtype == np.int16:
            for i in range(abf.channelCount):
                raw[i] = np.multiply(raw[i], abf._dataGain[i])
                raw[i] = np.add(raw[i], abf._dataOffset[i])
        return raw
```

**Comment by shadowk29** [comment]
Two bugs, but otherwise works well:

sampleCount needs to be cast to int:

```sampleCount = **int**((endTime - startTime) * abf.sampleRate)```

and the load of raw data needs to take into account that the abf file might have more than one channel of interleaved data when loading:

```raw = np.fromfile(fb, dtype=abf._dtype, count=(**abf.channelCount***sampleCount)```
