### ISSUE TITLE
should ATFstorage be an ABF class argument?

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#30]
When using a custom stimulus waveform, ATF stimulus waveforms are supported with [abf.py#L35](https://github.com/swharden/pyABF/blob/master/src/pyabf/abf.py#L35) which uses [atf_reader.py](https://github.com/swharden/pyABF/blob/master/src/pyabf/atf_reader.py) and [atf_storage.py](https://github.com/swharden/pyABF/blob/master/src/pyabf/atf_storage.py) to cache ATF files and load them in as an ABF class argument.

**Should `atfStorage=ATFStorage` really be an ABF class argument?**

> This feels odd because this seems like a rare case (ABF files with ATF stimulus files), yet its made its way all the way to become an argument in the primary class of this entire project. It works as it is, but I'm preparing to port this project to C# (re-writing it from scratch) so I want to make sure everything is in its most logical spot.

An alternative way to get the same functionality is just to have the user do the work of reading and caching these files themselves. The tools can still be available with pyABF, just imported _outside_ the ABF class. Perhaps even an ATF class would be useful.

```python
import pyabf

abf = pyabf.ABF("data.abf")
abf.epochsByChannel = pyabf.ATF("stim.atf").epochsByChannel

# then all the usual python code works
print(abf.sweepX, abf.sweepY)
print(abf.sweepX, abf.sweepC)
```

Although, does it really make sense to call it epochs at all at that point? Why not just keep the stimulus data outside the ABF class forever? This would mean you'd write use-case-based analysis code as needed:

```python
import pyabf

stim = pyabf.ATF("stim.atf")
abf = pyabf.ABF("data.abf")

# then write your custom program as needed
print(abf.sweepX, abf.sweepY)
print(abf.sweepX, stim.sweepC)
```

I'm leaning toward this, because it makes it easy to maintain the ATF code and ATF code doesn't live inside of the _ABF_ class...

**Comment by swharden** [comment]
**Distilling the issue:** It would be good for custom stimulus waveforms to be supported by the ABF class so that calling `abf.sweepC` doesn't return an array of `NaN` values (the current behavior), but instead returns the stimulus waveform.

Currently, `abf.sweepC` is created here:
https://github.com/swharden/pyABF/blob/master/src/pyabf/abf.py#L148-L155

**Possible solution:** Perhaps this is where the modification should occur. Perhaps a new ABF class variable `abf.stimulusWaveform` could be used. If it's `False` (default), `abf.sweepC` returns what it does now. If it's populated, `abf.sweepC` returns `abf.stimulusWaveform`. This would let the user use any arbitrary custom waveform (generated with a math equation, an ATF file, ABF file, WAV file, or whatever) and only a few lines of the ABF core class need to be involved.

**Comment by t-b** [comment]
@swharden Thanks for merging the PR so quickly.

I did not touch the ABF interface more for the ATFStorage class to fit in better as I don't think the current interface properly separates the different tasks at hand.

The ABF class seems to be some kind of wrapper around ABFcore which does baseline subtraction (something I would say is out of the scope for this class), averaging (dito), average error (dito) and has a stateful interface, setSweep, which makes reading out the sweeps more hassle than it could be. And why is `sweepC` part of ABF but sweepD, sweepX, sweepY part of ABFCore?

At the moment the ABF __init__ is also the only function of the ABF class which accepts parameters which allows to tweak how the ABF files are loaded. The interface could be changed to 

 ```python

 class ABFLoader:

  def __init__(self, filepath, **kwargs):
        self.name = filepath
        # atfstorage handling
        # preloadData handling
        # channel for loading only data from a particular channel

  def __iter__(self):
      # Returns an sweep object with all channels given in the __init__ argument
      # data of sweepX, sweepY, sweepC precalculation according to __init__ arguments
```

I would not consider adding functions like `set_atf_storage` and `enable_preloading`  as that complicate the use of the class.

The averaging and the baseline calculation could then be separated classes accepting these sweep objects so you could do:

```
for sweep in pyabf.ABF('somefile'):
   average = Average(sweeps)
```

In general I think that the stimulus waveform is as important as the acquired data so both should be part of the same interface.

**Comment by t-b** [comment]
Regarding the stimulus waveform interface:

One can also think about having a classes which consume ABFCore and then generate the required data.

```python

class StimulusWaveform:

   def __init__(self, abfCore, atf_storage, sweep, channel):

   def __iter__(): # allows to iterate over all epochs, returns an Epoch object
```

PS: These class designs are all pretty ad-hoc ...

**Comment by swharden** [comment]
@t-b Thanks for the thoughtful comments! 

You've definitely convinced me that the handling of custom stimulus waveforms is functionality which indeed belongs inside the ABF class. I'm reminded of this in the fact that the [quickstart example on the pyABF home page](https://github.com/swharden/pyABF#quickstart) demonstrates simplistic access to command waveforms, so getting custom stimuli into the ABF class with maximum simplicity should be a goal of this project! Hopefully the solution we come up with can support ABF, ATF, and arbitrary (math equation, CSV, who knows) waveforms. I'll ponder this some more and hopefully come up with a good solution this weekend!

Your comments about sweep baseline subtraction and averaging are well received! I agree they should be removed from the ABFcore class, and have opened a ticket to track progress of this goal. https://github.com/swharden/pyABF/issues/31

Thanks again @t-b for your input!

**Comment by swharden** [comment]
The condensation of ABF & ABFcore classes will aim to continue to support of the ATF-loading class discussed here. Progress will be tracked on https://github.com/swharden/pyABF/issues/31

**Comment by swharden** [comment]
I just pulled the branch, and there are a _lot_ of internal changes. Most interactions with the ABF class remain unchanged. Of note:

* I rewrote a lot of the `ATFReader` class and renamed it to `ATF` and gave it similar methods as the `ABF` class. I left a little demo code at the bottom: https://github.com/swharden/pyABF/blob/master/src/pyabf/atf.py
* If an epoch-table-based waveform is detected as being used, `abf.sweepC` synthesizes and returns that waveform.
* If a custom waveform file is in use (ABF or ATF), `abf.sweepC` reads the content of that file and returns its data automatically, regardless of file type.
* To override the automatic-lookup behavior `abf.sweepC` performs when it is accessed (as seems to be the goal above), simply look-up your own stimulus waveform once and assign it to `abf.sweepC`. An example of this is here: https://github.com/swharden/pyABF/blob/master/dev/python/2018-08-22%20custom%20stimulus.py
* If you want to cache many stimulus waveforms, place them in a dictionary and make the key the stimulus filename. Then after instantiating an ABF, assign like `abf.sweepC = signalByFileName[stimulusFileName]`. Note that this name in the abf is available as `abf._StringsIndexed.lDACFilePath`

If the caching solution is not sufficient for your needs, please post some ABFs, stimulus waveforms, and example code you use to analyze them so we can redesign the ABF as needed to ensure your use case is supported. 

I think these recent changes solve many of the issues raised above, and if nothing else have largely improved the class structure of this project.
