### ISSUE TITLE
abfDateTime return string, not DateTime object

### ISSUE THREAD

**Issue by automated-reckoning** [swharden/pyABF#33]
Tested on pyabf-2.0.20 and pyabf-2.0.19. Returns DateTime object in 2.0.9, which I chose at random because I really need to get some files processed. 
Version 2.0.17 returns a DateTime object correctly.

**Comment by automated-reckoning** [comment]
Ah. Except it's telling me they're several weeks off of when they were actually created. Looks like it must have been a regression when fixing a datetime bug.

**Comment by swharden** [comment]
Hi @automated-reckoning, thanks for letting me know about it!

I revered `abf.DateTime` to a _datetime_ object which seems logical and is consistent with previous versions. I made a new `abf.DateTimeString` for people who only want to work with the text.

### sample code
```python
abf=pyabf.ABF(PATH_DATA+"/model_vc_ramp.abf")
print(type(abf.abfDateTime), abf.abfDateTime)
print(type(abf.abfDateTimeString), abf.abfDateTimeString)
```
### output
```
<class 'datetime.datetime'> 2017-11-27 08:17:59.810000
<class 'str'> 2017-11-27T08:17:59.810000
```

Let me know if you have any other issues! I committed this change https://github.com/swharden/pyABF/commit/2c62ec85b57fafe745cb40e24f77f58d7b91fae5 so it should be ready to go immediately (via the GitHub download, not yet on pypi)
