### ISSUE TITLE
clarify byte size of header items

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#49]
According to the struct format, `"i"` and `"l"` are both 4-byte integers. Make it clear in the source code these are to be read identically. Currently, `i` and `l` are used interchangeably. Maybe it means something to [C89](https://en.wikipedia.org/wiki/ANSI_C#C89), but not to Python.

https://docs.python.org/2/library/struct.html#format-characters

https://github.com/swharden/pyABF/blob/02ef67ded481278336776db04419c725c2d72ff9/src/pyabf/abfHeader.py#L279-L307

**Comment by t-b** [comment]
@swharden Longs are a bit ill-defined concept in C/C++. Prefering `i` is the way to go.
