### ISSUE TITLE
magnitude problem in ABF when change by Calmpfit.

### ISSUE THREAD

**Issue by samuelgarcia** [swharden/pyABF#5]
In neo with have also a AxonIO which is basically what pyabf do.

@Emerson207  is reporting a strange problem here:
https://github.com/NeuralEnsemble/python-neo/issues/533

Maybe we can try to resolve it evrywhere (neo + pyabf).

**Comment by swharden** [comment]
Hi @samuelgarcia thanks for this ticket!

## Assessment of the problem

Thanks to your message, I have ensured pyABF (v2) supports 32-bit floating point ABFs, such as the one you referenced. I have added these files to [the pyABF demo data section](https://github.com/swharden/pyABF/tree/master/data), but unfortunately the magnitude (scaling) problem remains.

I can provide slightly information though. Here are the full header breakdowns of the two files:
* [original file header](https://github.com/swharden/pyABF/blob/master/data/headers/2018_04_13_0016a_original.md) (16-bit integers)
* [clampfit-modified header](https://github.com/swharden/pyABF/blob/master/data/headers/2018_04_13_0016b_modified.md) (32-bit floats)

When I inspect the differences between the two, nothing stands out. This makes me suspect that the additional scaling information is stored in sections of the header which are undocumented (and therefore unsupported by the open-source ABF reading options), maybe like _ScopeSection_. There are also 3 unused/unknown variables in the header which are different between the files. Not sure what they're for.

## Pretty good fix: multiply by -1/3
I have no idea why this works, but just multiplying each sweep by -1/3 gives you the data you want.

**code:**
```python
import pyabf
assert pyabf.__version__.startswith("2")

# plot the first file
abf = pyabf.ABF("2018_04_13_0016a_original.abf")
abf.setSweep(sweepNumber=0, channel=1)
plt.plot(abf.sweepX, abf.sweepY, label="original ABF")

# plot the second file on top of it
abf = pyabf.ABF("2018_04_13_0016b_modified.abf")
abf.setSweep(sweepNumber=0, channel=1)
mult = -(1/3)
plt.plot(abf.sweepX, abf.sweepY * mult, label="modified ABF")

# decorate the plot and zoom to an interesting area
plt.title("2018_04_13_0016 inspection (pyABF v2)")
plt.ylabel(abf.sweepLabelY)
plt.xlabel(abf.sweepLabelX)
plt.legend()
plt.axis([.005,.015,-150,350])
plt.show()
```

**output:**

![figure_1](https://user-images.githubusercontent.com/4165489/41804844-cdd8bc94-766b-11e8-913a-9b5853a6e739.png)

## Conclusion for pyABF
For now, I will make it a goal to only fully support _original_ ABF files which come right off the digitizer, not files modified by ClampFit. Ideally all analysis will be done with pyABF anyway, and opening ABFs and doing analysis in ClampFit is a bit antithetical to the goals of the pyABF project (a ClampFit-free world).

However, if you find that every 32-bit float ABF recorded just needs to be multiplied by -1/3, let me know and I can certainly cook that into the code as a permanent fix!
