### ISSUE TITLE
New API stable enough and new release

### ISSUE THREAD

**Issue by t-b** [swharden/pyABF#51]
I'm using pyABF in https://github.com/AllenInstitute/ipfx/blob/master/ipfx/x_to_nwb/ABFConverter.py in version 2.0.18.

Is the new API stable enough so that upgrading to it now makes sense?
If yes, could you create a pypi release before?

**Comment by swharden** [comment]
I'll review it this evening and update this ticket when a release is made! I've been using it quite a lot for the last few months and it is indeed very stable.

**Comment by swharden** [comment]
I just issued a release and updated PyPi. I have very high confidence in the stability of this release (relatively little has changed since the last release):
https://github.com/swharden/pyABF/releases/tag/2.0.23

**Comment by t-b** [comment]
@swharden Thanks for the quick release. I've ported my application to the new API and my tests showed that it works. I've only spotted that the custom protocol location is not available anymore, I've added that in #55. And some code cleanup in #54.
