### ISSUE TITLE
Returns error on python 2.7

### ISSUE THREAD

**Issue by rat-h** [swharden/pyABF#66]
UBUNTU server Python 2.7.12, pyABF was installed over pip with no problem.
simple script reads abf file:
```
import numpy as np
from matplotlib import pyplot as plt
import pyabf
from scipy.stats import gaussian_kde as silverman

rec = pyabf2.ABF(sys.argv[1])
```
returns an error:
```
python readABF2.py 2018_11_27_0010.abf 
WARNING: pyABF is only partially supported on Python versions <3.6
Traceback (most recent call last):
  File "readABF2.py", line 2, in <module>
    import pyabf
  File "/usr/local/lib/python2.7/dist-packages/pyabf/__init__.py", line 25, in <module>
    from pyabf.abf import ABF
  File "/usr/local/lib/python2.7/dist-packages/pyabf/abf.py", line 34, in <module>
    import pyabf.abfWriter
  File "/usr/local/lib/python2.7/dist-packages/pyabf/abfWriter.py", line 110
    def _demo_sweep_data(sweeps=3, sweepLengthSec=5, sampleRate=20_000):
                                                                     ^
SyntaxError: invalid syntax

```
The same result on Anaconda2-5.3.0-Linux-x86_64

**Comment by swharden** [comment]
@rat-h thank you for bringing this to my attention! A recent "improvement" used code with underscores in numeric literals ([PEP 515](https://www.python.org/dev/peps/pep-0515/)) which worked on Python 3.6 but temporarily broke 2.7 support. I have corrected this issue and issued a new release (pyabf 2.0.32) which should fix your issue. You can upgrade with:
```
pip install --upgrade pyabf
```

I also added code to the test suite to test against Python 2.7 so future code changes will be unlikely to break Python 2.7 support.
