### ISSUE TITLE
Type error when file has only one comment

### ISSUE THREAD

**Issue by Martin-Zeller** [swharden/pyABF#7]
When attempting to read in an .abf file with only one comment, the following error is shown:
" 'int' object is not iterable ", from line 77 in abf.py.

My crude solution so far is to replace lines 77-79 with the following (there should be a more elegant way, I think):

    if isinstance(self.commentTimes, int):
        self.commentTimesSec = self.commentTimes*self._abfHeader.header["fSynchTimeUnit"]/1e6
        self.commentTimeMin = self.commentTimesSec * 60
        self.commentSweeps = int(self.commentTimesSec/self.sweepLengthSec)
    else:
        self.commentTimesSec=[x*self._abfHeader.header["fSynchTimeUnit"]/1e6 for x in self.commentTimes]
        self.commentTimesMin=[x*60 for x in self.commentTimesSec]
        self.commentSweeps=[int(x/self.sweepLengthSec) for x in self.commentTimesSec]

On a related note, I would greatly appreciate a fix to issue #3 :D

**Comment by swharden** [comment]
I suspect this issue has been corrected in v2 (which was just merged to master).

I haven't updated pypi (so you can't `pip install --upgrade pyabf` quite yet), but if you're inspired to download the package from this GitHub page it should work for you.

Most core functionality is the same, and the [getting started guide](https://github.com/swharden/pyABF/tree/master/docs/getting-started) is the best place to learn how to use pyABF v2.
