### ISSUE TITLE
error in python 2 during installation over pip

### ISSUE THREAD

**Issue by rat-h** [swharden/pyABF#70]
Anaconda2-5.3.0 x86_64 + docker

Collecting pyabf
  Downloading https://files.pythonhosted.org/packages/cc/79/219b13055385d809f97661f32923c2cfdfea654ffc14abfe0d93a792dd88/pyabf-2.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    WARNING: pyABF is only partially supported on Python versions <3.6
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-CyRZZJ/pyabf/setup.py", line 3, in <module>
        import pyabf
      File "pyabf/__init__.py", line 16, in <module>
        from pyabf.abf import ABF
      File "pyabf/abf.py", line 39, in <module>
        import pyabf.tools.text
    ImportError: No module named tools.text

**Comment by swharden** [comment]
Thank you for reporting this @rat-h ! This is definitely a bug for Python 2.7. While I added tests to ensure Python 2.7 support does not break, it doesn't test the _install_ script. It looks like this bug might only affect the install script. Either way, I'll get a fix posted this evening! 

If you're in a pinch, you can install a previous version: `pip install --force-reinstall pyabf==2.0.35`

**Comment by swharden** [comment]
Hi @rat-h, I have corrected this issue in pyABF 2.1.5, thank you again for bringing it to my attention! You can upgrade with:
```
pip install --upgrade pyabf
```
I also updated my Python 2 test script to test the `setup.py` to ensure that continues to stay python 2.7 compatible.

**Comment by rat-h** [comment]
Hi Scott, 
Thank you for the bugfix. It seems pyabf works again for Python 2.
