### ISSUE TITLE
improve event detection

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#76]
Create analysis modules for
- [x] membrane test - `pyabf.tools.Memtest(abf)`
- [ ] action potential detection
- [ ] Spontaneous current detection
  - [ ] parameter-based
  - [ ] template-based

Then when it's all working
- [ ] refactor interfaces for maximum consistency
- [ ] provide documentation for all new modules
- [ ] add tests to ensure the API does not change

**Comment by Sverreg** [comment]
In the meantime I had success with combining pyABF with[ bluebrain's eFEL library](https://github.com/BlueBrain/eFEL) for event detection, AP analysis etc.

**Comment by swharden** [comment]
I'm _slowly_ moving in this direction with https://github.com/swharden/vsABF/blob/master/dev/ABF-Analyzer/readme.md so those interested in following the development of open-source event detection options may want to follow that project too.

Once it's all hashed out in C# (as part of vsABF) I'll port it to Python and include it with pyABF

**Comment by swharden** [comment]
pyabf 2.1.8 has membrane test and action potential detection tools built in. They're pretty crude and hidden away, but at least they're installed with pypi now.

I'll keep working on this and update the documentation with real examples when I finalize the API. Spontaneous event detection is still on the to-do list.

* Membrane test [example](https://github.com/swharden/pyABF/blob/master/dev/python/2019-07-15%20memtest.py) - the memtest module is pretty mature
* AP detection [example](https://github.com/swharden/pyABF/blob/master/dev/python/2019-07-15%20ap%20detection.py) - the AP detection module is rough

**Comment by swharden** [comment]
After a lot of consideration, no, I don't think we should do this.

pyABF is an ***interface*** to ABF files. It is not an analysis tool. 

Event detection is simply outside the scope of this library.
